
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from io import BytesIO

def generate_trip_pdf(trip):
    """
    Generates a PDF for the given trip object (TripPlan schema).
    Returns a BytesIO object containing the PDF data.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=1))
    
    story = []

    # --- Header ---
    title_style = styles["Title"]
    title_style.textColor = colors.HexColor("#6366f1") # Indigo color matching UI
    story.append(Paragraph(f"Trip to {trip.destination}", title_style))
    story.append(Spacer(1, 12))

    # --- Trip Overview / Stats ---
    # Create a small summary table
    data = [
        ["Duration", f"{trip.days} Days"],
        ["Budget Level", trip.budget_level.title()],
        ["Travelers", str(trip.travelers)],
        ["Est. Total Cost", f"INR {trip.estimated_total_budget:,.2f}" if trip.estimated_total_budget else "N/A"]
    ]
    
    table = Table(data, colWidths=[120, 300])
    table.setStyle(TableStyle([
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke),
    ]))
    story.append(table)
    story.append(Spacer(1, 24))

    # --- Overview Text ---
    story.append(Paragraph("<b>Overview</b>", styles["Heading2"]))
    story.append(Paragraph(trip.overview, styles["Normal"]))
    story.append(Spacer(1, 24))

    # --- Daily Plan ---
    story.append(Paragraph("<b>Your Itinerary</b>", styles["Heading2"]))
    story.append(Spacer(1, 12))

    daily_plan = trip.daily_plan
    # If it's a model, convert to dict, or access attrs. 
    # The TripPlan from main.py uses Pydantic/SQLModel objects.
    
    for day in daily_plan:
        # Day Header
        day_title = f"Day {day.day}: {day.title}"
        story.append(Paragraph(day_title, styles["Heading3"]))
        
        # Summary
        story.append(Paragraph(f"<i>{day.summary}</i>", styles["Normal"]))
        story.append(Spacer(1, 6))
        
        # Places list
        places_str = ""
        # places might be a list or a string depending on if it came from DB or API directly in some contexts
        # In main.py TripPlan: places is List[str]
        current_places = day.places
        if isinstance(current_places, str):
            current_places = current_places.split('\n')
            
        for place in current_places:
            story.append(Paragraph(f"• {place}", styles["Normal"]))
        
        story.append(Spacer(1, 12))

    # --- Tips ---
    if trip.tips:
        story.append(Spacer(1, 12))
        story.append(Paragraph("<b>Smart Tips</b>", styles["Heading2"]))
        tips_list = trip.tips
        if isinstance(tips_list, str):
            tips_list = tips_list.split('\n')
            
        for tip in tips_list:
             story.append(Paragraph(f"• {tip}", styles["Normal"]))

    # --- Footer ---
    story.append(Spacer(1, 48))
    footer_text = "Generated by AI Trip Planner"
    story.append(Paragraph(footer_text, styles["Italic"]))

    doc.build(story)
    buffer.seek(0)
    return buffer
